export const DISPLAY_RANDOM_CARD = 'DISPLAY_RANDOM_CARD';

export const DISPLAY_SELECTED_CARD = 'DISPLAY_SELECTED_CARD';

export const UPDATE_COUNT_AND_FLASHCARDS = 'UPDATE_COUNT_AND_FLASHCARDS';

export const SHOW_RANDOM_BOOLEAN = 'SHOW_RANDOM_BOOLEAN';
